### ISSUE TITLE
Problems upgrading from Zoph 0.9.0

### ISSUE THREAD

**Issue by Raysir** [jeroenrnl/zoph#88]
I am attempting to make a new install of Zoph 0.9.5 in a new linux machine running Kubuntu 16.04. I want to base this install off the data on another machine running Zoph 0.9.0. In the new machine I created a MySQL DB and imported the .sql from the old 0.9.0 machine. I placed a zoph.ini in the new machine at /etc. I put a fresh set of 0.9.5 files at the Apache web root from a fresh zoph-0.9.5.zip file.

I successively ran the zoph_update-0.9.1.sql and the zoph_update-0.9.2.sql on the DB from the old 0.9.0 install. When I tried to do the zoph_update-0.9.3.sql update, I got an error >> ALTER TABLE zoph_people ADD COLUMN createdby int(11) NOT NULL DEFAULT 1	Error Code: 1292. Incorrect date value: '0000-00-00' for column 'dob' at row 105. 

Conclusion >> zoph_update-0.9.3.sql will not run if there is a date of '0000-00-00' for column 'dob'. I have modified the date and now the zoph_update-0.9.3.sql will run but perhaps you want to fix this so others will not have the same problem.

Ray

**Comment by jeroenrnl** [comment]
I checked my database - obviously running v0.9.5 - and I have a few "0000-00-00" entries in the database. I never had the problem you describe. It has to do with the 'sql_mode' your MySQL server is in, in 'strict mode', dates like 0000-00-00 are not allowed. A simple ```UPDATE zoph_people SET dob=null WHERE dob="0000-00-00";``` fixes this. I will include those lines in the upgrade script for 0.9.6

**Comment by Raysir** [comment]
Thanks for your input. I am still having problems with the upgrade. The result is that essentially all screens have text with the last lines reading similar to then following:

> ORDER BY clause is not in SELECT list, references column 'zophempty.pp.position' which is not in SELECT list; this is incompatible with DISTINCT Fatal Error: SQL failed db.inc.php: 156.
> fatal error

Could the problem be that even though I ran the zoph_update MySQL files successively, I did not run the corresponding .php code for each version? I jumped all the way to the Zoph 0.9.5 code. Is that necessary?
My Apache Zoph directory reads as follows:
.
├── classes
├── interfaces 
├── js                                                                                                                                                                                                             
├── lang
├── templates
├── traits
├── xml
├── actions.inc.php
├── admin.php
├── album.php
├── albums.php
├── ....

Ar the outset, I made a MySQL database as follows:

> create database zophempty;
> CREATE USER 'zoph_rw'@'localhost' IDENTIFIED BY 'Pwd******';
> GRANT ALL PRIVILEGES ON zophempty.* TO 'zoph_rw'@'localhost';

After the above, I imported my version 0.9.0. database into this new DB, then I did the successive zoph_updates.

I made a zoph.ini file and placed this at /etc. It contains the following:

> db_host = "localhost"
> db_name = "zophempty"
> db_user = "zoph_rw"
> db_pass = "Pwd******"
> db_prefix = "zoph_"
> 
> php_location = "/var/www/html/zoph"


Any suggestions would be greatly appreciated,
Ray

**Comment by jeroenrnl** [comment]
First, it's not needed to run any php scripts during update, the process you followed is the correct one.
Could you see if changing line 399 in ```classes\photo.inc.php```
from
```$qry->addFields(array("last_name", "first_name", "called"));```
into
```$qry->addFields(array("last_name", "first_name", "called", "pp.position"));```
fixes this?

**Comment by Raysir** [comment]
Thanks for the confirmation on the process I used.

Changing the line you suggested in classes\photo.inc.php does not solve the problem. In fact, I don't see that it makes any difference. One point however, the classes\photo.inc.php file that I downloaded in zoph-0.9.5.zip does not have a line 399. It is just a blank line (same as line 401). I made the changes as shown below:
```
        $qry->addFields(array("person_id"), $distinct);
//        $qry->addFields(array("last_name", "first_name", "called"));
$qry->addFields(array("last_name", "first_name", "called", "pp.position"));
        $where=new clause("pp.photo_id=:photoid");
```
I should point out that I am running:
* Apache  2.4.18
* PHP 7.0.8
* MySQL mysql-server 5.7.17
* ImageMagick 7.0.4-7 Q16 x86_64 2017-02-10

On a Kubuntu machine Version 16.04
* session >> session.save_path	/var/lib/php/sessions
* pcre >>PCRE (Perl Compatible Regular Expressions) Support 	enabled 
* gd2  >> GD Support 	enabled 
* exif  >> EXIF Support 	enabled 
* xml  >> libXML support 	active 
* pear (if you want to use the e-mail features) (not installed)
* FileInfo >>  fileinfo support 	enabled 

I am happy to try anything you suggest.
Ray

**Comment by jeroenrnl** [comment]
Correct, it should have been 398, I had added some debug output before it, which caused the lines to shift by one.

So, you say, the error appears on the bottom of almost every page? Could you be more specific? The line I changed is the only line I could find that could cause this error, but it will cause an error below the photo on each photo.php - not on every page.
Is there more output before the error you posted, maybe with line numbers?

The problem is caused by a change in MySQL 5.7.x, which has not been made in MariaDB 10.x - which I am using, so I can't reproduce it, only make an educated guess...

**Comment by Raysir** [comment]
OK, I have now restored line 398 to what it was originally.
[Here](http://frieds.org/AdditionalPages/PeopleShot.jpg) is what the people page looks like. The text for it reads as follows:


>     George Brown #0 db\db::query(db\select Object ([db\selectjoins] => Array ([0] => INNER JOIN zoph_photo_people AS ppl ON p.photo_id=ppl.photo_id),[db\selectgroupby] => Array (),[*union] => Array (),[*subquery] => ,[*table] => zoph_photos,[*tables] => Array ([p] => photos,[ppl] => photo_people),[*alias] => p,[*fields] => Array ([0] => DISTINCT p.photo_id,[1] => p.name,[2] => p.path,[3] => p.width,[4] => p.height),[*params] => Array ([0] => db\param Object ([db\paramname] => :personId,[db\paramvalue] => 2,[db\paramtype] => 1)),[*where] => db\clause Object ([db\clauseclause] => ppl.person_id=:personId,[db\clausesubclauses] => ),[*having] => ,[*order] => Array ([0] => p.date asc,[1] => p.time asc,[2] => p.photo_id asc),[*count] => 1,[*offset] => 0)) called at [/var/www/html/zoph/classes/zophTable.inc.php:616] #1 zophTable::getRecordsFromQuery(db\select Object ([db\selectjoins] => Array ([0] => INNER JOIN zoph_photo_people AS ppl ON p.photo_id=ppl.photo_id),[db\selectgroupby] => Array (),[*union] => Array (),[*subquery] => ,[*table] => zoph_photos,[*tables] => Array ([p] => photos,[ppl] => photo_people),[*alias] => p,[*fields] => Array ([0] => DISTINCT p.photo_id,[1] => p.name,[2] => p.path,[3] => p.width,[4] => p.height),[*params] => Array ([0] => db\param Object ([db\paramname] => :personId,[db\paramvalue] => 2,[db\paramtype] => 1)),[*where] => db\clause Object ([db\clauseclause] => ppl.person_id=:personId,[db\clausesubclauses] => ),[*having] => ,[*order] => Array ([0] => p.date asc,[1] => p.time asc,[2] => p.photo_id asc),[*count] => 1,[*offset] => 0)) called at [/var/www/html/zoph/photo_search.inc.php:478] #2 get_photos(Array ([person_id] => 2), 0, 1, , user Object ([person] => person Object ([home] => ,[work] => ,[fields] => Array ([person_id] => 1,[first_name] => Unknown,[last_name] => Person2,[middle_name] => ,[called] => ,[gender] => ,[dob] => ,[dod] => ,[home_id] => ,[work_id] => ,[father_id] => ,[mother_id] => ,[spouse_id] => ,[notes] => ,[coverphoto] => ,[pageset] => ,[email] => ,[createdby] => 1)),[prefs] => prefs Object ([prefscolorScheme] => ,[fields] => Array ([user_id] => 1,[show_breadcrumbs] => 1,[num_breadcrumbs] => 8,[num_rows] => 3,[num_cols] => 4,[max_pager_size] => 10,[random_photo_min_rating] => 0,[reports_top_n] => 5,[color_scheme_id] => 4,[slideshow_time] => 5,[language] => ,[recent_photo_days] => 7,[auto_edit] => 0,[camera_info] => 1,[allexif] => 0,[autocomp_albums] => 1,[autocomp_places] => 1,[autocomp_categories] => 1,[autocomp_photographer] => 1,[autocomp_people] => 1,[fullsize_new_win] => 0,[view] => list,[autothumb] => highest,[child_sortorder] => sortname)),[lang] => language Object ([iso] => en,[name] => English ,[languagefilename] => lang/en,[languagetranslations] => Array ()),[fields] => Array ([user_id] => 1,[person_id] => 1,[user_class] => 0,[view_all_photos] => 1,[delete_photos] => 1,[user_name] => admin,[password] => $2y$10$cFl.NZJDITXBg6Etl3udd.JpNkgzsRIwBoJf7f5AWqi9Itv1HJY6q,[browse_people] => 1,[browse_places] => 1,[browse_tracks] => 1,[edit_organizers] => 1,[detailed_people] => 1,[see_hidden_circles] => 1,[detailed_places] => 1,[import] => 1,[download] => 1,[leave_comments] => 1,[allow_rating] => 1,[allow_multirating] => 0,[allow_share] => 0,[lightbox_id] => ,[lastnotify] => ,[lastlogin] => 2017-02-24 16:46:43,[lastip] => 127.0.0.1))) called at [/var/www/html/zoph/classes/person.inc.php:351] #3 person->getPhotoCount() called at [/var/www/html/zoph/templates/default/blocks/view_list.tpl.php:34] #4 include(/var/www/html/zoph/templates/default/blocks/view_list.tpl.php) called at [/var/www/html/zoph/classes/template/template.inc.php:123] #5 template\template->__toString() called at [/var/www/html/zoph/classes/template/template.inc.php:210] #6 template\template->displayBlocks() called at [/var/www/html/zoph/templates/default/organizer.tpl.php:45] #7 include(/var/www/html/zoph/templates/default/organizer.tpl.php) called at [/var/www/html/zoph/classes/template/template.inc.php:123] #8 template\template->__toString() called at [/var/www/html/zoph/people.php:172] SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'zophempty.p.date' which is not in SELECT list; this is incompatible with DISTINCT Fatal Error: SQL failed db.inc.php: 156.
>     fatal error

The Albums | View photos page produces

```
#0 db\db::query(db\select Object ([db\selectjoins] => Array ([0] => INNER JOIN zoph_photo_albums AS pa ON p.photo_id=pa.photo_id),[db\selectgroupby] => Array (),[*union] => Array (),[*subquery] => ,[*table] => zoph_photos,[*tables] => Array ([p] => photos,[pa] => photo_albums),[*alias] => p,[*fields] => Array ([0] => DISTINCT p.photo_id,[1] => p.name,[2] => p.path,[3] => p.width,[4] => p.height),[*params] => Array ([0] => db\param Object ([db\paramname] => :albumId,[db\paramvalue] => 2,[db\paramtype] => 1)),[*where] => db\clause Object ([db\clauseclause] => pa.album_id=:albumId,[db\clausesubclauses] => ),[*having] => ,[*order] => Array ([0] => p.date asc,[1] => p.time asc,[2] => p.photo_id asc),[*count] => 12,[*offset] => 0)) called at [/var/www/html/zoph/classes/zophTable.inc.php:616] #1 zophTable::getRecordsFromQuery(db\select Object ([db\selectjoins] => Array ([0] => INNER JOIN zoph_photo_albums AS pa ON p.photo_id=pa.photo_id),[db\selectgroupby] => Array (),[*union] => Array (),[*subquery] => ,[*table] => zoph_photos,[*tables] => Array ([p] => photos,[pa] => photo_albums),[*alias] => p,[*fields] => Array ([0] => DISTINCT p.photo_id,[1] => p.name,[2] => p.path,[3] => p.width,[4] => p.height),[*params] => Array ([0] => db\param Object ([db\paramname] => :albumId,[db\paramvalue] => 2,[db\paramtype] => 1)),[*where] => db\clause Object ([db\clauseclause] => pa.album_id=:albumId,[db\clausesubclauses] => ),[*having] => ,[*order] => Array ([0] => p.date asc,[1] => p.time asc,[2] => p.photo_id asc),[*count] => 12,[*offset] => 0)) called at [/var/www/html/zoph/photo_search.inc.php:478] #2 get_photos(Array ([album_id] => 2), 0, 12, , user Object ([person] => person Object ([home] => ,[work] => ,[fields] => Array ([person_id] => 1,[first_name] => Unknown,[last_name] => Person2,[middle_name] => ,[called] => ,[gender] => ,[dob] => ,[dod] => ,[home_id] => ,[work_id] => ,[father_id] => ,[mother_id] => ,[spouse_id] => ,[notes] => ,[coverphoto] => ,[pageset] => ,[email] => ,[createdby] => 1)),[prefs] => prefs Object ([prefscolorScheme] => ,[fields] => Array ([user_id] => 1,[show_breadcrumbs] => 1,[num_breadcrumbs] => 8,[num_rows] => 3,[num_cols] => 4,[max_pager_size] => 10,[random_photo_min_rating] => 0,[reports_top_n] => 5,[color_scheme_id] => 4,[slideshow_time] => 5,[language] => ,[recent_photo_days] => 7,[auto_edit] => 0,[camera_info] => 1,[allexif] => 0,[autocomp_albums] => 1,[autocomp_places] => 1,[autocomp_categories] => 1,[autocomp_photographer] => 1,[autocomp_people] => 1,[fullsize_new_win] => 0,[view] => list,[autothumb] => highest,[child_sortorder] => sortname)),[lang] => language Object ([iso] => en,[name] => English ,[languagefilename] => lang/en,[languagetranslations] => Array ()),[fields] => Array ([user_id] => 1,[person_id] => 1,[user_class] => 0,[view_all_photos] => 1,[delete_photos] => 1,[user_name] => admin,[password] => $2y$10$cFl.NZJDITXBg6Etl3udd.JpNkgzsRIwBoJf7f5AWqi9Itv1HJY6q,[browse_people] => 1,[browse_places] => 1,[browse_tracks] => 1,[edit_organizers] => 1,[detailed_people] => 1,[see_hidden_circles] => 1,[detailed_places] => 1,[import] => 1,[download] => 1,[leave_comments] => 1,[allow_rating] => 1,[allow_multirating] => 0,[allow_share] => 0,[lightbox_id] => ,[lastnotify] => ,[lastlogin] => 2017-02-24 16:46:43,[lastip] => 127.0.0.1))) called at [/var/www/html/zoph/photos.php:69] SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'zophempty.p.date' which is not in SELECT list; this is incompatible with DISTINCT Fatal Error: SQL failed db.inc.php: 156.
fatal error

```
The Photos | View photos page produces the following:

```
> #0 db\db::query(db\select Object ([db\selectjoins] => ,[db\selectgroupby] => Array (),[*union] => Array (),[*subquery] => ,[*table] => zoph_photos,[*tables] => Array ([p] => photos),[*alias] => p,[*fields] => Array ([0] => DISTINCT p.photo_id,[1] => p.name,[2] => p.path,[3] => p.width,[4] => p.height),[*params] => ,[*where] => ,[*having] => ,[*order] => Array ([0] => p.date asc,[1] => p.time asc,[2] => p.photo_id asc),[*count] => 12,[*offset] => 0)) called at [/var/www/html/zoph/classes/zophTable.inc.php:616] #1 zophTable::getRecordsFromQuery(db\select Object ([db\selectjoins] => ,[db\selectgroupby] => Array (),[*union] => Array (),[*subquery] => ,[*table] => zoph_photos,[*tables] => Array ([p] => photos),[*alias] => p,[*fields] => Array ([0] => DISTINCT p.photo_id,[1] => p.name,[2] => p.path,[3] => p.width,[4] => p.height),[*params] => ,[*where] => ,[*having] => ,[*order] => Array ([0] => p.date asc,[1] => p.time asc,[2] => p.photo_id asc),[*count] => 12,[*offset] => 0)) called at [/var/www/html/zoph/photo_search.inc.php:478] #2 get_photos(Array (), 0, 12, , user Object ([person] => person Object ([home] => ,[work] => ,[fields] => Array ([person_id] => 1,[first_name] => Unknown,[last_name] => Person2,[middle_name] => ,[called] => ,[gender] => ,[dob] => ,[dod] => ,[home_id] => ,[work_id] => ,[father_id] => ,[mother_id] => ,[spouse_id] => ,[notes] => ,[coverphoto] => ,[pageset] => ,[email] => ,[createdby] => 1)),[prefs] => prefs Object ([prefscolorScheme] => ,[fields] => Array ([user_id] => 1,[show_breadcrumbs] => 1,[num_breadcrumbs] => 8,[num_rows] => 3,[num_cols] => 4,[max_pager_size] => 10,[random_photo_min_rating] => 0,[reports_top_n] => 5,[color_scheme_id] => 4,[slideshow_time] => 5,[language] => ,[recent_photo_days] => 7,[auto_edit] => 0,[camera_info] => 1,[allexif] => 0,[autocomp_albums] => 1,[autocomp_places] => 1,[autocomp_categories] => 1,[autocomp_photographer] => 1,[autocomp_people] => 1,[fullsize_new_win] => 0,[view] => list,[autothumb] => highest,[child_sortorder] => sortname)),[lang] => language Object ([iso] => en,[name] => English ,[languagefilename] => lang/en,[languagetranslations] => Array ()),[fields] => Array ([user_id] => 1,[person_id] => 1,[user_class] => 0,[view_all_photos] => 1,[delete_photos] => 1,[user_name] => admin,[password] => $2y$10$cFl.NZJDITXBg6Etl3udd.JpNkgzsRIwBoJf7f5AWqi9Itv1HJY6q,[browse_people] => 1,[browse_places] => 1,[browse_tracks] => 1,[edit_organizers] => 1,[detailed_people] => 1,[see_hidden_circles] => 1,[detailed_places] => 1,[import] => 1,[download] => 1,[leave_comments] => 1,[allow_rating] => 1,[allow_multirating] => 0,[allow_share] => 0,[lightbox_id] => ,[lastnotify] => ,[lastlogin] => 2017-02-24 16:46:43,[lastip] => 127.0.0.1))) called at [/var/www/html/zoph/photos.php:69] SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'zophempty.p.date' which is not in SELECT list; this is incompatible with DISTINCT Fatal Error: SQL failed db.inc.php: 156.
> fatal error
```
I hope this helps. Please let me know of additional information you need.
Ray

**Comment by jeroenrnl** [comment]
I'm installing a MySQL server now, so I can test the changes without you having to make all the changes manually, because from the above output, I see that quite a few changes have to be made.

**Comment by Raysir** [comment]
Good! I am here to help in any way you suggest - just not very skilled in these technologies but I really like Zoph!

Ray

**Comment by jeroenrnl** [comment]
I have a running MySQL server now and I can reproduce the issue. It will probably take a few days to fix all of them. If you want a workaround for the time being, you can remove ```ONLY_FULL_GROUP_BY``` from the line that starts with ```sql_mode=``` in ```/etc/mysql/my.cnf``` and restart MySQL

**Comment by Raysir** [comment]
Good! Glad you can reproduce the problem there. I will stand by for your solution.

Thanks,
Ray

**Comment by jeroenrnl** [comment]
It turned out to be more work than I thought, but I have just pushed several changes. You can download a snapshot of the 'hotfix' branch [here](https://github.com/jeroenrnl/zoph/archive/hotfix.zip). You will need to run the ``zoph_update-0.9.5.1.sql`` script to perform the upgrade. The upgrade process is similar to other Zoph upgrades. If you need detailed instructions, I'd be happy to provide them.

**Comment by Raysir** [comment]
Thanks but so far it still doesn't run. I ran the zoph_update-0.9.5.1.sql update on my database but get the same results as previous attempts.  

At this point I think it would be informative if I did a complete new install of Zoph then import a few photos. Do you agree? Can I use everything in the zoph-hotfix.zip file to build the new install? In other words, should I just use the zoph-hotfix/sql/zoph.sql to set up the tables? In that case, I would **not** run the zoph_update-0.9.5.1.sql. I would use the php scripts in the zoph-hotfix/php directory.

I am open to your suggestions.

Thanks,
Ray

**Comment by jeroenrnl** [comment]
No need to do a full reinstall, but you do need to install the .php files that are in the .zip file, as if you are doing a regular upgrade of Zoph.

If you do want to run a full install, you will need to run ``zoph.sql`` AND ``zoph_update-0.9.5.1.sql``, because I have not yet incorporated the changes into ``zoph.sql``. But again, this should not be necesary.

**Comment by Raysir** [comment]
I have now done a complete install (detailed below). When I hit http://localhost/NewZoph/logon.php
I got a message >> Fatal Error: No php_location setting in /etc/zoph.ini found that matches /var/www/html/NewZoph settings.inc.php: 93.
fatal error

Here are the install steps I followed:
**Made a MySQL database**
create database zophempty CHARACTER SET utf8 COLLATE utf8_general_ci"
CREATE USER 'zoph_rw'@'localhost' IDENTIFIED BY 'Pwd****';
GRANT ALL PRIVILEGES ON zophempty.* TO 'zoph_rw'@'localhost';
Installed the tables ie zoph.sql >>> CREATE TABLE zoph_albums (etc..
Tried to run the zopy_update-0.9.5.1 but got the following:
Action
UPDATE zoph_users SET person_id=NULL WHERE person_id=0
Response
Error Code: 1175. You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column To disable safe mode, toggle the option in Preferences -> SQL Editor and reconnect.
Took MySQL out of safe mode (Edit | Preferences | SQL Editor and set to “Safe Updates” and re-ran, update worked this time.

**zoph.ini**
Placed this at /etc. It contains the following:
```
[production]
db_host = "localhost"
db_name = "zophempty"
db_user = "zoph_rw"
db_pass = "Pwd****"
db_prefix = "zoph_"

php_location = "/var/www/html/NewZoph/"
```
Set the permissions on this file to Owner > www-data, UserGroup > ray, Permissions > -rw-rw-rw-

**Setting up PHP templates**
Put all the directories and files that were in the in /zoph-hotfix.zip/zoph-hotfix/php directory into /var/www/html/NewZoph. This is 331 files, 27 sub-folders however I did not copy the sql, contrib and cli directories. There is a question here as to weather the cli directory should be copied too. The 
I set the permissions on this directory to Owner > www-data, UserGroup > ray, Permissions > -rw-r-r-

**Photo Directory**
This is at /var/Zoph with permissions Owner > www-data, UserGroup > root, Permissions > drwxrwxrwx. I have not defined this directory location in any of the setup steps so far. Hopefully it will come later!

**Placing cli in path**
$ echo $PATH 
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle
/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin 

I copied /zoph-hotfix/cli/zoph to /bin The owner is root, user group is root, permissions are -rwxr-xr-x

**Hitting the site**
I hit http://localhost/NewZoph/logon.php
Got a message >> Fatal Error: No php_location setting in /etc/zoph.ini found that matches /var/www/html/NewZoph settings.inc.php: 93.
fatal error

Where did I go wrong? How to fix this??
Thanks,
Ray

**Comment by jeroenrnl** [comment]
@Raysir It took me some experimenting on my own system before I spotted it: you should remove the trailing ``/`` from ``php_location`` in ``zoph.ini``

**Comment by Raysir** [comment]
Thank you - that solved the immediate problem that I listed above. I am sorry to cause you all the problem. Now with that fixed, I still found that I could not change values in the Home >> Adminpage >> **Configuration** page. I could enter the desired changes and click on Submit then if I would refresh the configuration page, all values would revert back to their default. I worked around this by changing the values in the /var/www/html/NewZoph/classes/conf/**confDefault.inc.php** page. I was able to then change the $intWidth, $pathImage, $importEnable, and the $importUpload. I was then able to import photos. 
I still get a crash when I attempt to add people or places. When attempting to add people, I get the following: 
```
string(540) "#0 /var/www/html/NewZoph/classes/db/db.inc.php(147): PDOStatement->execute() #1 /var/www/html/NewZoph/classes/db/query.inc.php(279): db\db::query(Object(db\insert)) #2 /var/www/html/NewZoph/classes/db/insert.inc.php(76): db\query->execute() #3 /var/www/html/NewZoph/classes/zophTable.inc.php(249): db\insert->execute() #4 /var/www/html/NewZoph/classes/person.inc.php(79): zophTable->insert() #5 /var/www/html/NewZoph/actions.inc.php(40): person->insert() #6 /var/www/html/NewZoph/person.php(58): require_once('/var/www/html/N...') #7 {main}" INSERT INTO zoph_people (last_name, first_name, middle_name, called, gender, dob, dod, email, home_id, work_id, mother_id, father_id, spouse_id, notes, createdby) VALUES("one", "more", "", "", "1", "", "", "", "", "", "", "", "", " ", "1") ;SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'dob' at row 1 Fatal Error: SQL failed db.inc.php: 157.
fatal error
```
Obviously there are some things that are not working. Certainly I have write access to the MySQL table as the photos that I imported are reflected in the zophempty.zoph_photos table. [Here](http://frieds.org/AdditionalPages/ApacheDocRoot.jpg) is the owners and permissions associated with the NewZoph scripts. Please notice the owner and permissions leading down to the NewZoph directory (/var/www/html/NewZoph).

Looking forward to your suggestions. 

Thanks,
Ray

**Comment by jeroenrnl** [comment]
@Raysir the configuration problems could be caused by some values not being the correct format, two settings I always need to change after a new install are the "Salt for sharing mid/full size images". In my browser (Firefox), the value turns red and scrolls into view, but that may not be the case in all browsers. Although, there might be something else going on, because this should not cause the values to turn back to default.

The second error you gave is one from the big change I made a few days ago that I missed. I will work on that as soon as I'm at my dev PC.

**Comment by jeroenrnl** [comment]
I've made a fix for the SQL error you got. You could either apply the patch from the change just above this or download a snapshot from the issue#88 branch and install that.

**Comment by jeroenrnl** [comment]
@Raysir I've also done some tests on the configuration page, but cannot reproduce your issue. My best guess is still that you have not added the "Salt for sharing mid/full size images" but for some reason your browser doesn't highlight that. Which browser (incl. version) are you using?

**Comment by jeroenrnl** [comment]
Patch for the SQL error: https://github.com/jeroenrnl/zoph/commit/eac68e854595804f1ed577786010ad946c279fdd.patch
Issue#88 snapshot: https://github.com/jeroenrnl/zoph/archive/issue%2388.zip

**Comment by Raysir** [comment]
We are making progress! I installed the Issue#88 snapshot (everything in zoph-issue-88/php) and now the People problem is solved. I have changed the Salt as you suggested and now the changes that I make to the Home >> Adminpage >> **Configuration** page are accepted and remembered. I am using Firefox 52.0 (64-bit).

I still get a crash when attempting to add Places. Here is the text that is generated:
```
string(621) "#0 /var/www/html/NewZoph/classes/db/db.inc.php(147): PDOStatement->execute() #1 /var/www/html/NewZoph/classes/db/query.inc.php(279): db\db::query(Object(db\insert)) #2 /var/www/html/NewZoph/classes/db/insert.inc.php(76): db\query->execute() #3 /var/www/html/NewZoph/classes/zophTable.inc.php(249): db\insert->execute() #4 /var/www/html/NewZoph/classes/zophTreeTable.inc.php(46): zophTable->insert() #5 /var/www/html/NewZoph/classes/place.inc.php(96): zophTreeTable->insert() #6 /var/www/html/NewZoph/actions.inc.php(40): place->insert() #7 /var/www/html/NewZoph/place.php(40): require_once('/var/www/html/N...') #8 {main}" INSERT INTO zoph_places (title, parent_place_id, address, address2, city, state, zip, country, url, urldesc, lat, lon, mapzoom, notes, createdby) VALUES("Wed Night", "1", "", "", "", "", "", "", "", "", "", "", "0", "", "1") ;SQLSTATE[01000]: Warning: 1265 Data truncated for column 'lat' at row 1 Fatal Error: SQL failed db.inc.php: 157.
fatal error
```
I am able to set up new Categories now.

By the way, if I set the Screen width on the Configuration page to anything less than 1000px, the top level tabs wrap. See [shot ](http://frieds.org/AdditionalPages/TabWrap.jpg)to see what they look like with Screen width = 900px. This wrapping occurs independent of browser View Zoom setting and occurs on both Firefox and Chromium Version 56.0.2924.76.

Another thing, several years ago, you guided me in a fix to make the hyperlink target area associated with [Prev] and [Next] larger. I has some users attempting to use mobile devices. They had a very difficult time touching in the correct spot to activate the Prev and Next links. The solution you suggested solved this problem however I don't think that enlarged area is included in the current version. It would be helpful if it was.

Thanks,
Ray

**Comment by jeroenrnl** [comment]
About the places error: fix has been added. You can again download the issue#88 snapshot (https://github.com/jeroenrnl/zoph/archive/issue%2388.zip)

I am aware of the menu wrapping at less than 900px - it's the reason I changed the default to 1000px. This should work on nearly all computer screens, but telephones may be an issue. At this moment Zoph is not "responsive" and it's very hard to make it, because I'm still not done moving all parts of Zoph into templates (see issue #8) , which is a lot of work with a big chance of breaking things, so I'm trying to somewhat restrict the amount of changes I make in each version. I'm planning on moving another batch in the v0.9.6 release, but it really depends on time.

For the Prev and Next links, @lizdodd raised issue #89 for that, which I'm also planning on integrating in the next release (v0.9.6). I'm not sure why the solution I previously made never made into a release...

**Comment by Raysir** [comment]
OK - but still not there. I installed the snapshot and now like you say, I can set up new places however when I attempt to assign this new location to an existing photo by selecting the new location then clicking update, I get a fatal error. See below:
```
string(312) "#0 /var/www/html/NewZoph/classes/db/db.inc.php(147): PDOStatement->execute() #1 /var/www/html/NewZoph/classes/db/query.inc.php(279): db\db::query(Object(db\update)) #2 /var/www/html/NewZoph/classes/zophTable.inc.php(358): db\query->execute() #3 /var/www/html/NewZoph/photo.php(251): zophTable->update() #4 {main}" UPDATE zoph_photos SET title="", location_id="2", lat="", lon="", mapzoom="0", date="2010-05-29", time="10:30:46", time_corr="0", view="", photographer_id="", level="1", description="" WHERE (photo_id=3);SQLSTATE[01000]: Warning: 1265 Data truncated for column 'lat' at row 1 Fatal Error: SQL failed db.inc.php: 157.
fatal error
```
This kind of error also now occurs when I attempt to assign a pre-established category to an existing photo. The ability to assign pre-established categories worked with the first Issue#88 snapshot however that seems to be broken now. I now get a red X when selecting a category - even before clicking update.  In fact, I am now getting a red X when attempting to make most any kind of change to a photo.

I understand the menu wrapping issue when the width is not wide enough. That is understandable and I can set the width to 1000px.

Standing by for your input,

Ray

**Comment by jeroenrnl** [comment]
Another fix. Again,download the issue#88 snapshot. 
I've made a small change to the database too (drop a field that was not used anymore), so you'll have to execute the last line from ``zoph_update-0.9.5.1.sql`` (the other lines in that file you have already executed).

**Comment by Raysir** [comment]
Wonderful!! I executed the sql line and installed the latest snapshot and as far as I can tell, all things are working as I expected! Thanks! 

Next I will try this latest code on the the install that was made from an old .0.9.0 install on a different machine. Will take several days to try that out again but I will let you know what I find.
Ray

**Comment by jeroenrnl** [comment]
I'm closing the issue, feel free to reopen if you find anything.
